functional:
  - Сайт должен предоставлять возможность регистрации и входа для пользователей.
  - На платформе должны быть доступны задачи по программированию различной сложности.
  - Пользователи могут фильтровать задачи по языку программирования.
  - Каждая задача должна иметь описание условия и подсказки.
  - После решения задачи пользователь должен видеть свой результат и возможные улучшения.
  - Зарегистрированные пользователи могут создавать и управлять собственными задачами.
  - Пользователи могут следить за написанием кода других во время решения задачи.
  - Доступно соревнование как с ботами, так и с реальными людьми.
  - Пользователи могут создавать игры с настраиваемыми параметрами.
  - В профиле пользователя доступна статистика его деятельности.
  - Перевод заданий между английским и русским языками.
  - Проверка правильности кода и возможность сдаться.
  - Чат с соперником и общение на главной странице.

non-functional:
  - Загрузка страниц сайта не должна превышать 3 секунды.
  - Все данные пользователей должны храниться в зашифрованном виде.
  - Сайт должен быть оптимизирован для мобильных устройств.
  - Должны обеспечиваться удобство использования, быстродействие и безопасность.
  - Сайт должен работать разлияных версиями браузеров.
  - Должна быть доступна мобильная версия сайта.
  - Сайт должен быть способен обрабатывать большие объемы трафика.

implicit:
  - Интерфейс сайта должен быть понятным для пользователей всех уровней подготовки.
  - Сайт должен регулярно обновляться новыми задачами и функциональностями.
  - Пользователи могут сохранять прогресс и историю решенных задач.
  - Нельзя изменять параметры игры после её создания.
