---
functional:
  - Сайт должен предоставить вомзожность зарегистрироваться через Email, GitHUb или Discord
  - Пользователи должны иметь возможность просматривать код других участников в процессе решения задач.
  - Платформа должна поддерживать соревнования как с ботами, так и с реальными пользователями.
  - Пользователи могут создавать свои собственные игры, настраивая их параметры (сложность, продолжительность, тип противника и т. д.).
  - Возможность просмотра статистики своей деятельности, включая результаты соревнований и выполненные задачи.
  - Пользователи могут выбирать язык программирования для решения задач.
  - Участники могут просматривать условия задач во время тгры.
  - Поддержка перевода условий задач с английского на русский и наоборот.
  - Возможность сброса решения задачи до начального состояния.
  - Возможность проверки корректности представленного кода.
  - Пользователи могут сдаться, прекратив участие в задаче.
  - Возможность общения с соперниками через чат.
  - Возможность общения с другими участниками на главной странице платформы.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен корректно работать на резных версиях браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Задание должно быть понятным и не содержать ошибок, которые могут повлиять на игру
  - Возможность получения уведомлений о входящих сообщениях или если кто-то пригласил пользователя в игру.
  - Пользователь не может менять параметры начатой игры
  - Пользователь не может принимать участие в нескольких играх одновременно
