---
functional:
  - У пользователя должна быть возможность зарегистрироваться на сайте
  - У пользователя должна быть возможность авторизоваться через GitHub или Discord
  - У пользователя должна быть возможность выбора игры против рандомного соперника, друга или бота
  - У пользователя должна быть возможность посмотретра статистики своих игр
  - У пользователя должна быть возможность выбора уровень сложности, тип игры, временные рамки и задачу в игре
  - У пользователя должна быть возможность выбрать язык программирования для задачи
  - У пользователя должна быть возможность выбрать язык программирования для профиля
  - У пользователя должна быть возможность выброра языка для текста задачи в игре ( RU / ENG)
  - У пользователя должена быть возможность сдаться
  - Сайт должен отображать рейтинг игроков
  - У пользователя должна быть возможность посмотреть статистику других игроков
  - У пользователя должна быть возможность посмотреть информиацию о прошлых играх
  - У пользователя должна быть возможность возможность создавать турниры
  - У пользователя должна быть возможность общаться в чате с соперником
  - У пользователя должна быть возможность присоединиться к созданной другим участником игре или турниру
non-functional:
  - Сайт должен иметь безопасное соединение
  - Сайт должен иметь мобильную версию
  - Сайт должен корректно работать с современными версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен быть интуитивно понятен
  - Все атрибуты сайта должны быть выполнены кооректно сверстаны, никакой из элементов не должен вылезать из своих границ
  - Победа должна присваиваться игроку который верно решил задачу первым
